# Generated by Django 3.0.6 on 2020-06-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUtilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyelectricitycr',
            old_name='login',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='historygascr',
            old_name='login',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='historywatercr',
            old_name='login',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='lastcounterreading',
            old_name='login',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='login',
            new_name='username',
        ),
    ]
