# Generated by Django 3.0.6 on 2020-06-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUtilities', '0002_auto_20200604_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyelectricitycr',
            old_name='username',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='historygascr',
            old_name='username',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='historywatercr',
            old_name='username',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='lastcounterreading',
            old_name='username',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='username',
            new_name='login',
        ),
    ]
