# Generated by Django 3.0.6 on 2020-06-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUtilities', '0003_auto_20200604_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historygascr',
            name='first_account',
            field=models.CharField(default='RJ_545-45', max_length=50, verbose_name='Лицевой счет Газ'),
        ),
        migrations.AlterField(
            model_name='historywatercr',
            name='first_account',
            field=models.CharField(blank=True, default='RJ_545-45', max_length=50, verbose_name='Лицевой счет Вода'),
        ),
    ]
