# Generated by Django 3.0.6 on 2020-06-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUtilities', '0004_auto_20200604_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historygascr',
            old_name='login',
            new_name='username',
        ),
    ]
