# Generated by Django 3.0.6 on 2020-06-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUtilities', '0006_auto_20200604_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyelectricitycr',
            old_name='login',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='historywatercr',
            old_name='login',
            new_name='username',
        ),
    ]
