# Generated by Django 3.0.6 on 2020-06-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUtilities', '0007_auto_20200605_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historygascr',
            name='username',
        ),
        migrations.AddField(
            model_name='historygascr',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppUtilities.Profile', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
