# Generated by Django 3.0.6 on 2020-06-05 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUtilities', '0008_auto_20200605_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historygascr',
            name='login',
        ),
        migrations.AddField(
            model_name='historygascr',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
