# Generated by Django 3.0.6 on 2020-06-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUtilities', '0010_auto_20200605_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='login',
        ),
        migrations.AddField(
            model_name='services',
            name='id_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppUtilities.Profile', verbose_name='ID Пользователя'),
            preserve_default=False,
        ),
    ]
