# Generated by Django 3.0.6 on 2020-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUtilities', '0012_auto_20200605_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id_user',
        ),
        migrations.AddField(
            model_name='services',
            name='id_service',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID Услуги'),
            preserve_default=False,
        ),
    ]
